@startuml

!theme plain

abstract Pregunta {
    - enunciado : String
    # Pregunta(enunciado : String, opciones : List<Opcion>, cantidadOpcionesMin : Int, cantidadOpcionesMax : Int
    + seleccionarOpcion(indice : Int): Opcion
    + {abstract} evaluarRespuestas(respuestas : List<Opcion>): Int
}

Class Opcion {
    - texto : String
    - esCorrecta : Bool
    + Opcion(texto : String, esCorrecta : Bool)
    + esCorrecta(): Bool
    + equals(opcion : Object): Bool
}

class ClassicTF {
    + ClassicTF(pregunta : String, respuesta : Bool)
    + evaluarRespuestas(respuestas : List<Opcion>): Int
}

class PenaltyTF {
    + PenaltyTF(pregunta : String, respuesta : Bool)
    + evaluarRespuestas(respuestas : List<Opcion>): Int
}

class ClassicMC {
    + ClassicMC(pregunta : String, opciones : List<Opcion>)
    + evaluarRespuestas(respuestas : List<Opcion>): Int
}

class PenaltyMC {
    + PenaltyMC(pregunta : String, opciones : List<Opcion>)
    + evaluarRespuestas(respuestas : List<Opcion>): Int
}

ClassicTF .up.|> Pregunta
ClassicMC .up.|> Pregunta
PenaltyTF .up.|> Pregunta
PenaltyMC .up.|> Pregunta

ClassicTF o-down- "2" Opcion
PenaltyTF o-down- "2" Opcion
ClassicMC o-down- "2..5" Opcion
PenaltyMC o-down- "2..5" Opcion

@enduml
