@startuml

hide circle
skinparam classAttributeIconSize 0
skinparam monochrome true

class Juego {
    + Juego(jugadores: List<Jugador>, preguntas : List<Pregunta>)
    + hacerPregunta(): Void
}

class Jugador {
    - nombre : String
    - puntos : Int
    + Jugador(nombre : String)
    + getPuntos(): Int
    + getNombre(): String
    + obtenerRespuestas(pregunta : Pregunta): List<Opcion>
    + modificarPuntos(puntos : Int): Void
}

abstract Pregunta {
    - enunciado : String
    # Pregunta(enunciado : String, opciones : List<Opcion>, cantidadOpcionesMin : Int, cantidadOpcionesMax : Int
    + seleccionarOpcion(indice : Int): Opcion
    + {abstract} evaluarRespuestas(respuestas : List<Opcion>): Int
}

class Opcion {
    - texto : String
    + Opcion(texto : String)
    + equals(opcion : Object): Bool
}

Juego o-down- "1..*" Pregunta
Juego o-left- "2..*" Jugador
Pregunta o-left- "2..*" Opcion

@enduml
