@startuml

!theme plain

class Juego {
    + Juego(jugadores: List<Jugador>, preguntas : List<Pregunta>)
    + hacerPregunta(): Void
}

class Jugador {
    - nombre : String
    - puntos : Int
    + Jugador(nombre : String)
    + obtenerRespuestas(...): List<Opcion>
    + getPuntos(): Int
    + sumarPuntos(puntos : Int): Void
}

abstract Pregunta {
    - enunciado : String
    + Pregunta(enunciado : String, opciones : List<Opcion>)
    + mostrarPregunta(): Void
    + {abstract} seleccionarOpcion(indice : Int): Opcion
    + {abstract} evaluarRespuestas(respuestas : List<Opcion>): Int
}

Class Opcion {
    - texto : String
    - esCorrecta : Bool
    + Opcion(texto : String, esCorrecta : Bool)
    + mostrarOpcion(): Void
    + esCorrecta(): Bool
}

class ClassicTF {
    + ClassicTF(pregunta : String, respuesta : Bool)
    + seleccionarOpcion(indice : Int): Opcion
    + evaluarRespuestas(respuestas : List<Opcion>): Int
}

class ClassicMC {
    + ClassicMC(pregunta : String, opciones : List<Opcion>)
    + seleccionarOpcion(indice : Int): Opcion
    + evaluarRespuestas(respuestas : List<Opcion>): Int
}

Juego o-down- "1..*" Pregunta
Juego o-left- "2..*" Jugador
Pregunta o-left- "2..*" Opcion
ClassicTF .up.|> Pregunta
ClassicMC .up.|> Pregunta

@enduml
